# Generated by Django 4.2.4 on 2023-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Basmati', 'Basmati'), ('Mwea Pishori', 'Mwea Pishori'), ('Jasmine Rice', 'Jasmine Rice'), ('Biryani Rice', 'Biryani Rice')], default='MWEA_PISHORI', max_length=50, null=True),
        ),
    ]
