# Generated by Django 4.2.4 on 2023-09-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
    ]
