# Generated by Django 4.2.6 on 2023-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0002_alter_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
