# Generated by Django 4.2.4 on 2023-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_quantity_in_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
