# Generated by Django 4.2.6 on 2023-11-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0003_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
