# Generated by Django 4.2.4 on 2023-09-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0004_stock_product_category_stock_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_quantity_in_stock',
        ),
    ]
