# Generated by Django 4.2.6 on 2023-10-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ricemart.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
