# Generated by Django 4.2.6 on 2023-11-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0008_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_in_stock',
        ),
    ]
