# Generated by Django 4.2.6 on 2023-10-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0009_orderstatus_paymentmethod_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
