# Generated by Django 4.2.6 on 2023-10-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0010_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='full_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
