# Generated by Django 4.2.6 on 2023-10-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricemart', '0012_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
