# Generated by Django 4.2.6 on 2023-10-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customeruser_status'),
        ('ricemart', '0013_remove_order_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateField(auto_now_add=True)),
                ('is_milled', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farmeruser')),
            ],
        ),
        migrations.CreateModel(
            name='MillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_milled', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date_milled', models.DateField(auto_now_add=True)),
                ('quantity_remaining', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farmeruser')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_stocked', models.IntegerField(blank=True, default=0, null=True)),
                ('date_stocked', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farmeruser')),
            ],
        ),
    ]
