# Generated by Django 4.2.4 on 2023-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customeruser_farmeruser_inventorymanageruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
