# Generated by Django 4.2.6 on 2023-10-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='verify',
        ),
    ]
