# Generated by Django 4.2.6 on 2023-11-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_verified_user_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='customer_id',
        ),
    ]
