# Generated by Django 4.2.6 on 2023-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
